services:
  - type: web
    name: sosens-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r app/requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: sosens-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: PYTHONPATH
        value: /opt/render/project/src

databases:
  - name: sosens-db
    plan: free
    databaseName: sosens
    user: sosens_user