services:
  - type: static_site
    name: sosens-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://sosens.onrender.com/api